import React, { useEffect, useState } from "react";
import { IdCard, Printer, Download, QrCode, RefreshCw, ShieldCheck, AlertCircle } from "lucide-react";
import toast from "react-hot-toast";
import { getMyIDCardApi } from "../../services/idCardService";
import IDCardTemplate from "../../components/idCards/IDCardTemplate";
import IDCardStatusBadge from "../../components/idCards/IDCardStatusBadge";

const MyIDCard = () => {
  const [idCard, setIdCard] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");
  const [orientation, setOrientation] = useState("Portrait");

  useEffect(() => {
    fetchMyCard();
  }, []);

  const fetchMyCard = async () => {
    try {
      setIsLoading(true);
      setError("");
      const res = await getMyIDCardApi();
      if (res?.success && res.data?.idCard) {
        setIdCard(res.data.idCard);
        if (res.data.idCard.cardOrientation) {
          setOrientation(res.data.idCard.cardOrientation);
        }
      } else {
        setIdCard(null);
      }
    } catch (err) {
      console.error(err);
      setError(
        err.response?.data?.message || "No active ID Card has been generated for your account."
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleOpenQRVerify = () => {
    if (!idCard) return;
    const verifyUrl = idCard.verificationToken
      ? `/verify-id-card/${idCard.verificationToken}`
      : `/verify-id/${idCard.cardNumber}`;
    window.open(verifyUrl, "_blank");
  };

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-3">
            <div className="rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 p-2.5 text-white shadow-md shadow-blue-500/20">
              <IdCard size={24} />
            </div>
            <div>
              <h1 className="text-2xl font-black tracking-tight text-slate-900">
                My Digital ID Card
              </h1>
              <p className="text-xs font-medium text-slate-500">
                View, download, or print your official corporate identity credential
              </p>
            </div>
          </div>
        </div>

        {idCard && (
          <div className="flex items-center space-x-2">
            <button
              onClick={() => setOrientation(orientation === "Portrait" ? "Landscape" : "Portrait")}
              className="px-3.5 py-2 rounded-xl border border-slate-200 bg-white text-xs font-bold text-slate-700 hover:bg-slate-50 shadow-2xs transition"
            >
              Toggle Orientation ({orientation})
            </button>

            <button
              onClick={handleOpenQRVerify}
              className="flex items-center space-x-1.5 px-4 py-2 rounded-xl border border-blue-200 bg-blue-50 text-blue-700 text-xs font-bold hover:bg-blue-100 transition"
            >
              <QrCode size={15} />
              <span>Verify QR</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-md shadow-blue-500/25 transition"
            >
              <Printer size={15} />
              <span>Print Card</span>
            </button>
          </div>
        )}
      </div>

      {/* Main Content Area */}
      {isLoading ? (
        <div className="py-20 flex flex-col items-center justify-center space-y-3 bg-white rounded-3xl border border-slate-100 shadow-xs">
          <RefreshCw className="animate-spin text-blue-600" size={32} />
          <p className="text-xs font-semibold text-slate-500">Retrieving your digital ID card...</p>
        </div>
      ) : !idCard ? (
        <div className="py-16 px-6 text-center bg-white rounded-3xl border border-slate-100 shadow-xs space-y-4 max-w-lg mx-auto">
          <div className="h-16 w-16 rounded-2xl bg-amber-50 text-amber-600 flex items-center justify-center mx-auto border border-amber-200">
            <AlertCircle size={32} />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-900">No Active ID Card</h3>
            <p className="text-xs text-slate-500 mt-1 leading-relaxed">
              {error || "Your official Employee ID Card has not been generated by HR or Admin yet."}
            </p>
          </div>
          <p className="text-[11px] text-slate-400">
            Please contact your HR Administrator or Office Admin to request your digital ID card generation.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* Render ID Card Preview */}
          <div className="lg:col-span-7 bg-slate-100 p-8 rounded-3xl border border-slate-200 flex flex-col items-center justify-center min-h-[480px]">
            <div className="mb-4 flex items-center space-x-2">
              <ShieldCheck size={16} className="text-emerald-600" />
              <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                Official Digital Identity Credential
              </span>
            </div>

            <div className="transform scale-95 sm:scale-100 origin-center transition-transform">
              <IDCardTemplate
                idCard={idCard}
                entityType={idCard.entityType || "employee"}
                orientation={orientation}
              />
            </div>
          </div>

          {/* Details Overview */}
          <div className="lg:col-span-5 bg-white p-6 rounded-3xl border border-slate-100 shadow-xs space-y-5">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-sm font-bold text-slate-900">Card Status & Information</h3>
              <IDCardStatusBadge status={idCard.status} />
            </div>

            <div className="space-y-3 text-xs">
              <div className="flex justify-between py-1 border-b border-slate-50">
                <span className="text-slate-500 font-medium">Card Number</span>
                <span className="font-mono font-bold text-slate-900">{idCard.cardNumber}</span>
              </div>

              <div className="flex justify-between py-1 border-b border-slate-50">
                <span className="text-slate-500 font-medium">Employee Code</span>
                <span className="font-bold text-slate-900">{idCard.partnerCode || idCard.displayId || "—"}</span>
              </div>

              <div className="flex justify-between py-1 border-b border-slate-50">
                <span className="text-slate-500 font-medium">Designation</span>
                <span className="font-bold text-blue-700">{idCard.designation}</span>
              </div>

              {idCard.department && (
                <div className="flex justify-between py-1 border-b border-slate-50">
                  <span className="text-slate-500 font-medium">Department</span>
                  <span className="font-bold text-slate-900">{idCard.department}</span>
                </div>
              )}

              <div className="flex justify-between py-1 border-b border-slate-50">
                <span className="text-slate-500 font-medium">Issue Date</span>
                <span className="font-medium text-slate-800">
                  {idCard.issueDate ? new Date(idCard.issueDate).toLocaleDateString("en-IN") : "—"}
                </span>
              </div>

              <div className="flex justify-between py-1 border-b border-slate-50">
                <span className="text-slate-500 font-medium">Expiry Date</span>
                <span className="font-bold text-blue-700">
                  {idCard.expiryDate ? new Date(idCard.expiryDate).toLocaleDateString("en-IN") : "—"}
                </span>
              </div>
            </div>

            <div className="rounded-2xl bg-blue-50/60 p-3 border border-blue-100 text-[11px] text-blue-800 leading-relaxed">
              <p className="font-bold mb-0.5">🔒 Official Verification Notice</p>
              Your digital ID card contains an encrypted QR verification link. Any authorized person scanning your QR code can verify your active corporate credentials.
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MyIDCard;
