const OFFICE_BASE = "/office-management";

const ROUTE_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER_CLIENT: "/register-client",
  REGISTER_PARTNER: "/register-partner",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  PRIVACY_POLICY: "/privacy-policy",
  DASHBOARD: "/dashboard",
  UNAUTHORIZED: "/unauthorized",
  ADMIN_DASHBOARD: "/admin/dashboard",
  SUPER_ADMIN_DASHBOARD: "/super-admin/dashboard",
  SUPER_ADMIN_CLIENTS: "/super-admin/clients",
  SUPER_ADMIN_EMPLOYEES: "/super-admin/employees",
  SUPER_ADMIN_Document_Uploads: "/super-admin/document-uploads",
  SUPER_ADMIN_EMPLOYEE_CREATE: "/super-admin/employees/create",
  SUPER_ADMIN_PROJECTS: "/super-admin/projects",
  SUPER_ADMIN_PROJECT_CREATE: "/super-admin/projects/create",
  SUPER_ADMIN_SERVICE_REQUESTS: "/super-admin/service-requests",
  SUPER_ADMIN_TASKS: "/super-admin/tasks",
  SUPER_ADMIN_TASK_CREATE: "/super-admin/tasks/create",
  SUPER_ADMIN_TEAMS: "/super-admin/teams",
  SUPER_ADMIN_TEAM_CREATE: "/super-admin/teams/create",
  SUPER_ADMIN_PAYROLL: "/super-admin/payroll",
  SUPER_ADMIN_PAYROLL_CREATE: "/super-admin/payroll/create",
  SUPER_ADMIN_INVOICES: "/super-admin/invoices",
  SUPER_ADMIN_INVOICES_Status: "/super-admin/invoices-status",
  SUPER_ADMIN_REPORTS: "/super-admin/reports",
  SUPER_ADMIN_SETTINGS: "/super-admin/settings",
  SUPER_ADMIN_SETTINGS_COMPANY_PROFILE: "/super-admin/settings/company-profile",
  SUPER_ADMIN_ATTENDANCE: "/super-admin/attendance",
  EMPLOYEE_DASHBOARD: "/employee/dashboard",
  EMPLOYEE_TASKS: "/employee/my-tasks",
  EMPLOYEE_PROJECTS: "/employee/projects",
  EMPLOYEE_ATTENDANCE: "/employee/attendance",
  EMPLOYEE_Document: "/employee/document-uploads",
  EMPLOYEE_BILLS: "/employee/bills",
  EMPLOYEE_PROFILE: "/employee/profile",
  EMPLOYEE_ID_CARD: "/employee/my-id-card",
  EMPLOYEE_CERTIFICATES: "/employee/my-certificates",
  CLIENT_DASHBOARD: "/client/dashboard",
  CLIENT_SUBMIT_SERVICE: "/client/submit-service",
  CLIENT_REQUESTS: "/client/my-requests",
  CLIENT_REQUEST_DETAILS: "/client/request",
  CLIENT_PROJECTS: "/client/projects",
  CLIENT_Document: "/client/document-uploads",
  CLIENT_INVOICES: "/client/invoices",
  CLIENT_SERVICE_DETAILS: "/client/service-details",
  CLIENT_SOCIAL_MEDIA_PACKAGES: "/client/social-media-packages",
  SUPER_ADMIN_SERVICE_DETAILS: "/super-admin/service-details",
  SUPER_ADMIN_CLIENT_DOCUMENTS: "/super-admin/client-documents",
  EMPLOYEE_SERVICE_DETAILS: "/employee/service-details",
  CLIENT_SERVICES: "/client/services",
  CLIENT_HISTORY: "/client/history",
  CLIENT_PROFILE: "/client/profile",
  REFERRAL_PARTNER_DASHBOARD: "/referral-partner/dashboard",
  SUPER_ADMIN_REFERRALS: "/super-admin/referrals",
  EMPLOYEE_REFERRALS: "/employee/referrals",
  REFERRAL_PARTNER_REFERRALS: "/referral-partner/referrals",
  SUPER_ADMIN_COMMISSIONS: "/super-admin/commissions",
  SUPER_ADMIN_PAYMENTS: "/super-admin/payments",
  REFERRAL_PARTNER_COMMISSIONS: "/referral-partner/commissions",
  REFERRAL_PARTNER_PAYMENTS: "/referral-partner/payments",
  SUPER_ADMIN_ID_CARDS: "/super-admin/id-cards",
  REFERRAL_PARTNER_ID_CARD: "/referral-partner/id-card",
  PUBLIC_VERIFY_ID: "/verify-id/:cardNumber",
  PUBLIC_VERIFY_ID_TOKEN: "/verify-id-card/:token",
  SUPER_ADMIN_CERTIFICATES: "/super-admin/certificates",
  REFERRAL_PARTNER_CERTIFICATES: "/referral-partner/certificates",
  PUBLIC_VERIFY_CERTIFICATE: "/verify-certificate/:certificateNumber",
  PUBLIC_VERIFY_CERTIFICATE_TOKEN: "/verify-certificate-token/:token",
  SUPER_ADMIN_NOTIFICATIONS: "/super-admin/notifications",
  REFERRAL_PARTNER_NOTIFICATIONS: "/referral-partner/notifications",
  SUPER_ADMIN_REPORTS_ANALYTICS: "/super-admin/reports-analytics",
  SUPER_ADMIN_DAILY_WORK_REPORTS: "/super-admin/daily-work-reports",
  REFERRAL_PARTNER_REPORTS: "/referral-partner/reports",
  REFERRAL_PARTNER_PROFILE: "/referral-partner/profile",
  REFERRAL_PARTNER_SUPPORT: "/referral-partner/support",
  SUPER_ADMIN_PARTNER_MANAGEMENT: "/super-admin/partner-management",
  SUPER_ADMIN_LEAVES: "/super-admin/leaves",
  EMPLOYEE_LEAVES: "/employee/leaves",
  SUPER_ADMIN_LEADS: "/super-admin/leads",
  SUPER_ADMIN_FOLLOWUPS: "/super-admin/follow-ups",
  SUPER_ADMIN_QUOTATIONS: "/super-admin/quotations",
  SUPER_ADMIN_ACCOUNTS: "/super-admin/accounts",
  SUPER_ADMIN_USERS: "/super-admin/users",
  SUPER_ADMIN_TENANTS: "/super-admin/tenants",
  SUPER_ADMIN_ADMIN_MANAGEMENT: "/super-admin/admin-management",
  SUPER_ADMIN_NOTICES: "/super-admin/notices",
  EMPLOYEE_NOTICES: "/employee/notices",
  EMPLOYEE_DAILY_WORK_REPORTS: "/employee/daily-work-reports",
  SUPER_ADMIN_REPORTS_EMPLOYEE: "/super-admin/reports/employee",
  SUPER_ADMIN_REPORTS_SALES: "/super-admin/reports/sales",
  SUPER_ADMIN_REPORTS_CLIENT: "/super-admin/reports/client",
  HR_DASHBOARD: "/hr/dashboard",
  HR_EMPLOYEES: "/hr/employees",
  HR_EMPLOYEE_CREATE: "/hr/employees/create",
  HR_EMPLOYEE_DETAILS: "/hr/employees/:id",
  HR_LEAVES: "/hr/leaves",
  HR_ATTENDANCE: "/hr/attendance",
  HR_PAYROLL: "/hr/payroll",
  HR_REPORTS: "/hr/reports",
  HR_HOLIDAYS: "/hr/holidays",
  HR_DOCUMENTS: "/hr/documents",
  HR_NOTICES: "/hr/notices",
  HR_MEETINGS: "/hr/meetings",
  HR_PROFILE: "/hr/profile",
  SUPER_ADMIN_HR_MANAGEMENT: "/super-admin/hr-management",
};

export const ROUTES = Object.fromEntries(
  Object.entries(ROUTE_PATHS).map(([key, path]) => {
    const sharedAuthRoute = new Set([
      "FORGOT_PASSWORD",
      "RESET_PASSWORD",
      "REGISTER_CLIENT",
      "REGISTER_PARTNER",
      "VERIFY_EMAIL",
    ]).has(key);

    return [
      key,
      sharedAuthRoute
        ? path
        : path === "/"
          ? OFFICE_BASE
          : `${OFFICE_BASE}${path}`,
    ];
  }),
);

export const ROLE_DASHBOARD_ROUTES = {
  super_admin: ROUTES.SUPER_ADMIN_DASHBOARD,
  admin: ROUTES.ADMIN_DASHBOARD,
  employee: ROUTES.EMPLOYEE_DASHBOARD,
  client: ROUTES.CLIENT_DASHBOARD,
  referral_partner: ROUTES.REFERRAL_PARTNER_DASHBOARD,
  hr: ROUTES.HR_DASHBOARD,
};


//super-admin/invoices?tab=payments SUPER_ADMIN_INVOICES